import { CreatorProfile, Playlist, Song, User } from './types';

export const MOCK_USERS: User[] = [
  { id: 'u1', email: 'alice@example.com', created_at: '2026-01-01T10:00:00Z', role: 'user' },
  { id: 'u2', email: 'bob@example.com', created_at: '2026-01-02T10:00:00Z', role: 'user' },
  { id: 'u3', email: 'admin@ai-music.com', created_at: '2026-01-03T10:00:00Z', role: 'admin' },
];

export const MOCK_CREATORS: CreatorProfile[] = [
  {
    id: 'u1',
    username: 'SynthwaveQueen',
    bio: 'Pioneering the next generation of retro-futuristic soundscapes using advanced AI generation.',
    avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&q=80',
    followers_count: 14200,
  },
  {
    id: 'u2',
    username: 'NeuralBeats',
    bio: 'Lofi & Chillhop generated by neural networks trained on 90s classics.',
    avatar_url: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&q=80',
    followers_count: 8500,
  },
];

export const MOCK_SONGS: Song[] = [
  {
    id: 's1',
    creator_id: 'u1',
    title: 'Neon Horizon',
    cover_url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&q=80',
    audio_url: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3', // Placeholder
    genre: 'Synthwave',
    mood: 'Energetic',
    language: 'Instrumental',
    description: 'An upbeat synthwave track perfect for night drives.',
    ai_tool: 'Suno AI',
    plays: 1250000,
    created_at: '2026-05-01T10:00:00Z',
  },
  {
    id: 's2',
    creator_id: 'u2',
    title: 'Midnight Rain',
    cover_url: 'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=800&q=80',
    audio_url: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3', // Placeholder
    genre: 'Lofi',
    mood: 'Chill',
    language: 'Instrumental',
    description: 'Relaxing lofi hip hop beats to study/relax to.',
    ai_tool: 'Udio',
    plays: 890000,
    created_at: '2026-05-15T12:00:00Z',
  },
  {
    id: 's3',
    creator_id: 'u1',
    title: 'Cybernetic Dreams',
    cover_url: 'https://images.unsplash.com/photo-1550684848-fac1c5b4e853?w=800&q=80',
    audio_url: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3', // Placeholder
    genre: 'Cyberpunk',
    mood: 'Dark',
    language: 'English',
    description: 'Heavy bass and gritty synth lines for a dystopian vibe.',
    ai_tool: 'Suno AI',
    plays: 245000,
    created_at: '2026-05-20T14:00:00Z',
  },
  {
    id: 's4',
    creator_id: 'u2',
    title: 'Coffee Shop Vibes',
    cover_url: 'https://images.unsplash.com/photo-1497935586351-b67a49e012bf?w=800&q=80',
    audio_url: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3', // Placeholder
    genre: 'Jazz',
    mood: 'Relaxing',
    language: 'Instrumental',
    description: 'Smooth AI jazz generation.',
    ai_tool: 'Suno AI',
    plays: 45000,
    created_at: '2026-05-25T14:00:00Z',
  }
];

export const MOCK_PLAYLISTS: Playlist[] = [
  {
    id: 'p1',
    user_id: 'u3',
    title: 'Top AI Hits 2026',
    cover_url: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=800&q=80',
    is_public: true,
    created_at: '2026-05-01T00:00:00Z',
  },
  {
    id: 'p2',
    user_id: 'u1',
    title: 'Coding Focus',
    cover_url: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800&q=80',
    is_public: true,
    created_at: '2026-05-10T00:00:00Z',
  }
];

export const MOCK_PLAYLIST_SONGS = [
  { playlist_id: 'p1', song_id: 's1', added_at: '2026-05-01T01:00:00Z' },
  { playlist_id: 'p1', song_id: 's3', added_at: '2026-05-21T01:00:00Z' },
  { playlist_id: 'p2', song_id: 's2', added_at: '2026-05-10T01:00:00Z' },
  { playlist_id: 'p2', song_id: 's4', added_at: '2026-05-26T01:00:00Z' },
];
